### Hae kaikki mediaesineet

get http://localhost:3000/api/media

### Hae media esitys

get http://localhost:3000/api/media/1

### Lisää media esitys

post http://localhost:3000/api/media
Content-Type: application/json


{
  "filename": "new_image.jpg",
  "filesize": 300000,
  "title": "New Image",
  "description": "Description of the new image",
  "user_id": 1607,
  "media_type": "image/jpeg",
  "created_at": "2023-10-20T15:00:00.000Z"
}